# Шрифт с анафемной торжественностью
font_family      Cinzel
bold_font        Cinzel Bold
italic_font      Cinzel Decorative
bold_italic_font Cinzel Decorative

font_size 14.0

# Цвета в духе Blasphemous
#foreground #e0dede
#background #1a0f13
foreground #e0dede
background #2c2c2c
background_opacity 0.60

# Выделение
selection_foreground #1a0f13
selection_background #c86f65

# Курсор (можно выбрать gothic red)
cursor #c84b4b

# Цвета палитры
color0  #1a0f13
color1  #c84b4b
color2  #6c7d47
color3  #b6a356
color4  #735380
color5  #a7668b
color6  #56847a
color7  #d8cbc5
color8  #4a3b3b
color9  #f38b82
color10 #a1ba77
color11 #d3c077
color12 #b89ade
color13 #e796c0
color14 #92c7b7
color15 #f1eae4

