font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0
adjust_line_height 2

foreground              #eadfff
background              #07040e
background_opacity      0.92
selection_foreground    #07040e
selection_background    #c88cff
cursor                  #c88cff
cursor_text_color       #07040e
url_color               #d9b2ff

window_padding_width 8
confirm_os_window_close 0
hide_window_decorations no

active_border_color   #b973ff
inactive_border_color #3a1b59
bell_border_color     #ff9ad5

color0  #12091d
color8  #4f3a69
color1  #c2578f
color9  #f08db9
color2  #7d6ee7
color10 #a79bff
color3  #d9b2ff
color11 #edd7ff
color4  #8c6cff
color12 #baa4ff
color5  #b973ff
color13 #d4a4ff
color6  #8fe1ff
color14 #b5efff
color7  #eadfff
color15 #ffffff
