$font = JetBrains Mono

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = soft, 0.22, 1, 0.36, 1
    animation = fadeIn, 1, 5, soft
    animation = fadeOut, 1, 5, soft
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = DP-3
    path = /home/halflight/.config/hypr/wallpapers/midir.jpg
    blur_passes = 1
    blur_size = 8
    noise = 0.008
    contrast = 1.0
    brightness = 0.34
    vibrancy = 0.22
    vibrancy_darkness = 0.0
}

shape {
    monitor = DP-3
    size = 620, 360
    color = rgba(7, 4, 14, 0.72)
    rounding = 22
    border_size = 2
    border_color = rgba(200, 140, 255, 0.42)
    position = 0, 0
    halign = center
    valign = center
}

shape {
    monitor = DP-3
    size = 660, 400
    color = rgba(0, 0, 0, 0.0)
    rounding = 28
    border_size = 1
    border_color = rgba(185, 115, 255, 0.24)
    position = 0, 0
    halign = center
    valign = center
}

shape {
    monitor = DP-3
    size = 540, 1
    color = rgba(240, 141, 185, 0.28)
    rounding = 0
    border_size = 0
    position = 0, 58
    halign = center
    valign = center
}

label {
    monitor = DP-3
    text = $TIME
    color = rgba(234, 223, 255, 0.96)
    font_size = 62
    font_family = $font
    position = 0, 92
    halign = center
    valign = center
}

label {
    monitor = DP-3
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgba(234, 178, 255, 0.78)
    font_size = 14
    font_family = $font
    position = 0, 42
    halign = center
    valign = center
}

input-field {
    monitor = DP-3
    size = 340, 58
    outline_thickness = 2
    inner_color = rgba(18, 9, 29, 0.92)
    outer_color = rgba(185, 115, 255, 0.78)
    check_color = rgba(200, 140, 255, 0.92)
    fail_color = rgba(240, 141, 185, 0.98)
    font_color = rgba(234, 223, 255, 1.0)
    fade_on_empty = false
    placeholder_text = password
    hide_input = true
    rounding = 16
    font_family = $font
    fail_text = wrong password
    fail_transition = 220
    capslock_color = rgba(255, 180, 210, 0.95)
    numlock_color = -1
    bothlock_color = rgba(255, 180, 210, 0.95)
    invert_numlock = false
    swap_font_color = false
    dots_spacing = 0.24
    dots_center = true
    dots_rounding = -1

    position = 0, -6
    halign = center
    valign = center
}

label {
    monitor = DP-3
    text = layout: $LAYOUT[EN,RU]  |  enter your user password
    color = rgba(234, 223, 255, 0.64)
    font_size = 12
    font_family = $font
    position = 0, -76
    halign = center
    valign = center
}
